pipeline:
  build:
    image: python:3-onbuild
    commands:
      - pip install -r requirements.txt
      - python manage.py test

services:
  postgres:
    image: postgres:9.5.2
    environment:
      - POSTGRES_USER=zazzuser
