# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zazzapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shout',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='shout',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
